version: '3'

services:
  cc-backend:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 5000:5000
      - 9229:9229
    command: npm start
    container_name: cc-backend
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge