version: '3'

services:
  cc-backend:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 5000:5000
      - 9229:9229
    command: npm start
    container_name: cc-backend
    networks:
      - app-network
  cc-database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: cc-database
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge